Proyecto1/urls.py
from django.contrib import admin
from django.urls import path
from AppMuebles.views import *
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", inicio, name="Inicio"),

    #URLS de los modelos creados
    #path("sur/", viaje_sur, name="Sur"),#
    path("sur/", ListaSur.as_view(), name="Sur"),

    #path("norte/", viaje_norte, name="Norte"),#
    path("norte/", ListaNorte.as_view(), name="Norte"),

    #path("centro/", viaje_centro, name="Centro"),#
    path("centro/", ListaCentro.as_view(), name="Centro"),

    #path("form_sur/", agregar_viajesur, name="nuevo viaje S"),#
    path("form_sur/", CrearSur.as_view(), name="nuevo viaje S"),

    #path("form_centro/", agregar_viajecentro, name="nuevo viaje C"),#
    path("form_centro/", CrearCentro.as_view(), name="nuevo viaje C"),

    #path("form_norte/", agregar_viajenorte, name="nuevo viaje N"),#
    path("form_norte/", CrearNorte.as_view(), name="nuevo viaje N"),

    path("buscar_viaje/", busqueda_viaje),
    path("resultadoViajes/", resultado_viaje),

    #path("actualizarSur/<sur_id>", actualizar_sur, name="Actualizar Sur"),#
    path("actualizarSur/<int:pk>", ActualizarSur.as_view(), name="Actualizar Sur"),

    #path("actualizarNorte/<norte_id>", actualizar_norte, name="Actualizar Norte"),#
    path("actualizarNorte/<int:pk>", ActualizarNorte.as_view(), name="Actualizar Norte"),

    #path("actualizarCentro/<centro_id>", actualizar_centro, name="Actualizar Centro"),#
    path("actualizarCentro/<int:pk>", ActualizarCentro.as_view(), name="Actualizar Centro"),

    #path("eliminarViajeSur/<sur_id>", eliminar_viaje_sur, name="Eliminar Sur"),
    path("eliminarViajeSur/<int:pk>", EliminarSur.as_view(), name="Eliminar Sur"),

    #path("eliminarViajeNorte/<norte_id>", eliminar_viaje_norte, name="Eliminar Norte"),
    path("eliminarViajeNorte/<int:pk>", EliminarNorte.as_view(), name="Eliminar Norte"),

    #path("eliminarViajeCentro/<centro_id>", eliminar_viaje_centro, name="Eliminar Centro"),
    path("eliminarViajeCentro/<int:pk>", EliminarCentro.as_view(), name="Eliminar Centro"),

    path("login/", inicio_sesion, name="iniciar sesion"),
    path("signup/", registro, name="registrarse"),
    path("logout/", cerrar_sesion, name="cerrar sesion"),
    path("edit/", editar_perfil, name="editar perfil"),
    path("sobremi/", sobre_mi, name="Sobre mi"),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppMuebles/models.py
from django.db import models
from django.contrib.auth.models import User

class Sur(models.Model):
    lugar = models.CharField(max_length=150)
    descripcion = models.CharField(max_length=3000)
    precio = models.IntegerField()

class Norte(models.Model):
    lugar = models.CharField(max_length=150)
    descripcion = models.CharField(max_length=3000)
    precio = models.IntegerField()

class Centro(models.Model):
    lugar = models.CharField(max_length=150)
    descripcion = models.CharField(max_length=3000)
    precio = models.IntegerField()

class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE) #Se puede editar cualquier models(como norte, sur, centro)
    image = models.ImageField(upload_to="avatars", null=True, blank=True)
    def __str__(self):
        return f"{self.usuario} --- {self.image}"

AppMuebles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SurForm(forms.Form):
    lugar = forms.CharField(max_length=150)
    descripcion = forms.CharField(max_length=3000)
    precio = forms.IntegerField()

class NorteForm(forms.Form):
    lugar = forms.CharField(max_length=150)
    descripcion = forms.CharField(max_length=3000)
    precio = forms.IntegerField()

class CentroForm(forms.Form):
    lugar = forms.CharField(max_length=150)
    descripcion = forms.CharField(max_length=3000)
    precio = forms.IntegerField()

class RegistrarUser(UserCreationForm):
    username = forms.CharField(label="Ingrese su nombre de usuario")
    email = forms.EmailField(label="Correo electronico")
    password1 = forms.CharField(label="Ingrese su contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirme su contraseña", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class EditarUser(UserCreationForm):
    username = forms.CharField(label="Editar su nombre de usuario")
    password1 = forms.CharField(label="Cambiar su contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar su contraseña nueva", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

AppMuebles/views.py
from django.shortcuts import render
from AppMuebles.forms import SurForm, NorteForm, CentroForm, RegistrarUser, EditarUser
from AppMuebles.models import Sur, Norte, Centro
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def inicio(request):
    return render(request, "AppMuebles/inicio.html")

def inicio_sesion(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            info = form.cleaned_data
            usuario = info["username"]
            contra = info["password"]
            usuario_actual = authenticate(username=usuario, password=contra)
            if usuario_actual is not None: #si el usuario actual es "algo" (encontro un usuario)
                login(request, usuario_actual) #iniciar sesion con este usuario
                return render(request, "AppMuebles/inicio.html", {"mensaje":f"Bienvenido {usuario}"})
            else: #no encuentra al usuario
                return render(request, "AppMuebles/inicio.html", {"mensaje":"Error, datos incorrectos"})
    else:
        form = AuthenticationForm()
    return render(request, "registro/inicio_sesion.html", {"formu":form})

def cerrar_sesion(request):
    logout(request)
    return render(request, "registro/cerrar_sesion.html")

def registro(request): 
    if request.method == "POST":
        formulario = RegistrarUser(request.POST) #la info del registro
        if formulario.is_valid():
            info = formulario.cleaned_data
            usuario = info["username"]
            formulario.save()
            return render(request, "AppMuebles/inicio.html", {"mensaje":f"Bienvenido {usuario}"})
    else:
        formulario = RegistrarUser()
    return render(request, "registro/register_user.html", {"formu":formulario})

def editar_perfil(request):
    usuario_actual = request.user
    if request.method == "POST":
        formulario = EditarUser(request.POST) #la info del registro
        if formulario.is_valid():
            info = formulario.cleaned_data
            usuario_actual.username = info["usuario"]
            usuario_actual.set_pasword(info["password1"])
            usuario_actual.save()
            return render(request, "AppMuebles/inicio.html")
    else:
        formulario = EditarUser(initial={"usuario":usuario_actual.username,
                                            "contraseña":usuario_actual.password})
    return render(request, "registro/editar_user.html", {"formu":formulario})


def busqueda_viaje(request):
    return render(request, "AppMuebles/buscar_viaje.html")


# def viaje_sur(request):
    return render(request, "AppMuebles/sur.html")

# def viaje_sur(request):
    via_sur = Sur.objects.all()
    info = {"sur1":via_sur}
    return render(request, "AppMuebles/sur.html", info)#

# def agregar_viajesur(request):
    if request.method == "POST":
        nuevo_formulario = SurForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data #lo volvemos diccionario
            sur_nuevo = Sur(lugar=info["lugar"], descripcion=info["descripcion"], precio=info["precio"])
            sur_nuevo.save() #lo guarda en la base de datos
            return render(request, "AppMuebles/inicio.html") #nos devuelve a inicio con los datos guardados
    else:
            nuevo_formulario = SurForm() #morstar formulario vacio
    return render(request, "AppMuebles/agregarviajesur.html", {"mi_formu":nuevo_formulario})#

# def actualizar_sur(request, sur_id):
    viaje_escogido= Sur.objects.get(lugar=sur_id)
    if request.method == "POST":
        nuevo_formulario = SurForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data #lo volvemos diccionario
            viaje_escogido.lugar= info["lugar"]
            viaje_escogido.descripcion= info["descripcion"]
            viaje_escogido.precio= info["precio"]
            viaje_escogido.save() #lo guarda en la base de datos
            return render(request, "AppMuebles/inicio.html") #nos devuelve a inicio con los datos guardados
    else:
            nuevo_formulario = SurForm(initial={"lugar":viaje_escogido.lugar, "descripcion":viaje_escogido.descripcion, "precio":viaje_escogido}) #morstar formulario vacio
    return render(request, "AppMuebles/update_sur.html", {"mi_formu":nuevo_formulario})#

# def eliminar_viaje_sur(request, sur_id):
    viaje_escogido= Sur.objects.get(lugar=sur_id)
    viaje_escogido.delete()
    return render(request, "AppMuebles/sur.html")

#---------------------------------------------------------------------------------------------------------------------------------------------------#


# def viaje_norte(request):
    return render(request, "AppMuebles/norte.html")

# def viaje_norte(request):
    via_norte = Norte.objects.all()
    info = {"norte1":via_norte}
    return render(request, "AppMuebles/norte.html", info)

# def agregar_viajenorte(request):
    if request.method == "POST":
        nuevo_formulario = NorteForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data
            norte_nuevo = Norte(lugar=info["lugar"], descripcion=info["descripcion"], precio=info["precio"])
            norte_nuevo.save()
            return render(request, "AppMuebles/inicio.html")
    else:
            nuevo_formulario = NorteForm() 
    return render(request, "AppMuebles/agregarviajenorte.html", {"mi_formu":nuevo_formulario})

# def actualizar_norte(request, norte_id):
    viaje_escogido2= Norte.objects.get(lugar=norte_id)
    if request.method == "POST":
        nuevo_formulario = NorteForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data #lo volvemos diccionario
            viaje_escogido2.lugar= info["lugar"]
            viaje_escogido2.descripcion= info["descripcion"]
            viaje_escogido2.precio= info["precio"]
            viaje_escogido2.save() #lo guarda en la base de datos
            return render(request, "AppMuebles/inicio.html") #nos devuelve a inicio con los datos guardados
    else:
            nuevo_formulario = NorteForm(initial={"lugar":viaje_escogido2.lugar, "descripcion":viaje_escogido2.descripcion, "precio":viaje_escogido2}) #morstar formulario vacio
    return render(request, "AppMuebles/update_norte.html", {"mi_formu2":nuevo_formulario})

# def eliminar_viaje_norte(request, norte_id):
    viaje_escogido2= Norte.objects.get(lugar=norte_id)
    viaje_escogido2.delete()
    return render(request, "AppMuebles/norte.html")

#------------------------------------------------------------------------------------------------------------------------------------------------------#

# def viaje_centro(request):
    return render(request, "AppMuebles/centro.html")

# def viaje_centro(request):
    via_centro = Centro.objects.all()
    info = {"centro1":via_centro}
    return render(request, "AppMuebles/centro.html", info)

# def agregar_viajecentro(request):
    if request.method == "POST":
        nuevo_formulario = CentroForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data
            centro_nuevo = Centro(lugar=info["lugar"], descripcion=info["descripcion"], precio=info["precio"])
            centro_nuevo.save()
            return render(request, "AppMuebles/inicio.html")
    else:
            nuevo_formulario = CentroForm()
    return render(request, "AppMuebles/agregarviajecentro.html", {"mi_formu":nuevo_formulario})

# def actualizar_centro(request, centro_id):
    viaje_escogido3= Centro.objects.get(lugar=centro_id)
    if request.method == "POST":
        nuevo_formulario = CentroForm(request.POST)
        if nuevo_formulario.is_valid():
            info = nuevo_formulario.cleaned_data #lo volvemos diccionario
            viaje_escogido3.lugar= info["lugar"]
            viaje_escogido3.descripcion= info["descripcion"]
            viaje_escogido3.precio= info["precio"]
            viaje_escogido3.save() #lo guarda en la base de datos
            return render(request, "AppMuebles/inicio.html") #nos devuelve a inicio con los datos guardados
    else:
            nuevo_formulario = CentroForm(initial={"lugar":viaje_escogido3.lugar, "descripcion":viaje_escogido3.descripcion, "precio":viaje_escogido3.precio}) #morstar formulario vacio
    return render(request, "AppMuebles/update_centro.html", {"mi_formu3":nuevo_formulario})

# def eliminar_viaje_centro(request, centro_id):
    viaje_escogido3= Centro.objects.get(lugar=centro_id)
    viaje_escogido3.delete()
    return render(request, "AppMuebles/centro.html")

#------------------------------------------------------------------------------------------------------------------------------------------#

def resultado_viaje(request):
    if request.method == "GET":
        viaje_pedido = request.GET["Viaje"]
        resultados_sur = Sur.objects.filter(lugar__icontains=viaje_pedido)
        resultados_norte = Norte.objects.filter(lugar__icontains=viaje_pedido)
        resultados_centro = Centro.objects.filter(lugar__icontains=viaje_pedido)
        resultados_viajes = list(resultados_sur) + list(resultados_norte) + list(resultados_centro)
    return render(request, "AppMuebles/buscar_viaje.html", {"viajes":resultados_viajes})

#CRUUD
class ListaSur(LoginRequiredMixin, ListView):
    model = Sur
    template_name = "AppMuebles/sur.html"

class CrearSur(CreateView):
    model = Sur
    template_name = "AppMuebles/agregarviajesur.html"
    fields = ["lugar", "descripcion", "precio"]
    success_url = "/sur/"

class ActualizarSur(UpdateView):
    model = Sur

AppMuebles/templates/AppMuebles/agregarviajecentro.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <h1>Agregar el viaje para el Centro</h1>
    <form action="" method="post"> {% csrf_token %} <!--es par que se agregue a la base de datos-->
        {{form.as_p}}
        <input type="submit" value="Guardar">
    </form>
{% endblock %}

AppMuebles/templates/AppMuebles/agregarviajenorte.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <h1>Agregar el viaje para el Norte</h1>
    <form action="" method="post"> {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Guardar">
    </form>
{% endblock %}

AppMuebles/templates/AppMuebles/agregarviajesur.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Viaje al sur</title>
</head>
<body>
    <h1>Agregar el viaje para el Sur</h1>
    <form action="" method="post"> {% csrf_token %}
        {{mi_formu.as_p}}
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

AppMuebles/templates/AppMuebles/buscar_viaje.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <h1>Donde les gustaria ir ?</h1>

    <form action="/resultadoViajes/" method="GET">
    Ingrese donde le gustaria viajar: <input type="text" name="Viaje">
    <input type="submit" value="Buscar">
    </form> 
    {% if viajes %}
    {% for x in viajes %}
    <h3 class="text-center">{{x.lugar}}</h3>
    {% endfor %}
    {% endif %}
{% endblock %}

AppMuebles/templates/AppMuebles/centro.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %} Aca vas a poder ver los paquetes que hay para el Centro de ARG {% endblock %}

{% block contenido1 %}
<ul>
    {% for x in object_list %}
        <li class="form">{{x.lugar}} - {{x.descripcion}} - Precio: {{x.precio}}</li>
    {% endfor %}
</ul>
<button class="btn btn-primary"><a class="navbar-brand" href="{% url 'nuevo viaje C' %}">Agregar viaje</a></button>
{% endblock %}

AppMuebles/templates/AppMuebles/eliminar_centro.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <form action="" method="post"> {% csrf_token %}
        <h3>¿Estas seguro de borrar el viaje "{{object}}"?</h3>
        <input type="submit" value="Eliminar">
    </form>
{% endblock %}

AppMuebles/templates/AppMuebles/eliminar_norte.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <form action="" method="post"> {% csrf_token %}
        <h3>¿Estas seguro de borrar el viaje "{{object}}"?</h3>
        <input type="submit" value="Eliminar">
    </form>
{% endblock %}

AppMuebles/templates/AppMuebles/eliminar_sur.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %}
    <form action="" method="post"> {% csrf_token %}
        <h3>¿Estas seguro de borrar el viaje "{{object}}"?</h3>
        <input type="submit" value="Eliminar">
    </form>
{% endblock %}

AppMuebles/templates/AppMuebles/inicio.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %} VIAJES POR LA ARGENTINA {% endblock %}

{% block contenido1 %} {{mensaje}} {% endblock %}

AppMuebles/templates/AppMuebles/norte.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %} Aca vas a poder ver los paquetes que hay para el Norte de ARG {% endblock %}

{{norte1}}

{% block contenido1 %}
<ul class="viajes">
    {% for x in object_list %}
        <li class="form">{{x.lugar}} - {{x.descripcion}} - Precio: {{x.precio}}</li>
    {% endfor %}
</ul>
<button class="btn btn-primary"><a class="navbar-brand" href="{% url 'nuevo viaje N' %}">Agregar viaje</a></button>
{% endblock %}

AppMuebles/templates/AppMuebles/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>VIAJES</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="{% static 'AppMuebles/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Inicio' %}">Pack de viajes para Argentina!!!</a>
                <a class="navbar-brand" href="{% url 'Sur' %}">Sur</a>
                <a class="navbar-brand" href="{% url 'Centro' %}">Centro</a>
                <a class="navbar-brand" href="{% url 'Norte' %}">Norte</a>
                <a class="navbar-brand" href="{% url 'Sobre mi' %}">Sobre mi</a>
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'cerrar sesion' %}">Cerrar sesión</a>
                <img src="{{ user.avatar_set.last.image.url }}" height="40px" width="40px">
                Hola {{user}}!
                {% else %}
                <a class="btn btn-primary" href="{% url 'registrarse' %}">Registrarse</a>
                <a class="btn btn-primary" href="{% url 'iniciar sesion' %}">Iniciar sesión</a>
                {% endif %}
            </div>
        </nav>
        {% block stylesadd %}<header class="masthead">{% endblock %}
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white" >
                            <h1 class="mb-5">{% block titulo %} {% endblock %}</h1>
                            {% block contenido1 %} {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Santiago Gorosito :D</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppMuebles/templates/AppMuebles/sobreMi.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %} Un poco sobre mi {% endblock %}

{% block contenido1 %}
    Me llamo Santiago, tengo 21 años y con la programación arranque hace mas de un año haciendo cursos como Desarrollo Web, JavaScript 2 veces, React js (por ahora todo Front End), actualmente me encuentro trabajando en una fabrica automotriz de 6am a 15pm y estudiando un curso de fullstack en la UTN, por eso mismo no me mate en hacer un re trabajo porque estoy a full jajaja. Me encantaría ejercer programación es algo que me gusta mucho y se me facilita al momento de aprender (lo mejor es cuando arreglo un error que me cuesta orrores en correjir, un alivio). La pagína iba a hacer de muebles por eso el "AppMuebles" pero cambie de opinion sobre la marcha para no complicarme mucho y no atrasarme en ningun curso sepan entendes y mil perdones🙏🏻. 
{% endblock %}

AppMuebles/templates/AppMuebles/sur.html
{% extends "AppMuebles/padre.html" %}

{% block titulo %} Aca vas a poder ver los paquetes que hay para el Sur de ARG {% endblock %}

{{sur1}}

{% block contenido1 %}
<ul>
    {% for x in object_list %}
        <li class="form">{{x.lugar}} - {{x.descripcion}} - Precio: {{x.precio}}</li>
    {% endfor %}
</ul>
<button class="btn btn-primary"><a class="navbar-brand" href="{% url 'nuevo viaje S' %}">Agregar viaje</a></button>
{% endblock %}